### ISSUE TITLE
Mateditor layout restore

### ISSUE THREAD

**Issue by tkpetersen** [WelSimLLC/WelSim-Apps#106]
For Mateditor:  When windows in the UI are accidentally closed, I find it impossible to restore the layout

**Comment by lcheng9** [comment]
Right click on the Toolbar area can show the menu to show or hide the windows. 
Also, a View menu is added to show/hide windows more intuitively. 

![matEditor_view_menu](https://github.com/user-attachments/assets/78fffc07-15fd-445d-8d1c-0492e81152c4)
