### ISSUE TITLE
Hyperelastic Polynomial 2nd order

### ISSUE THREAD

**Issue by disla2** [WelSimLLC/WelSim-Apps#14]
Polynomial 2nd order do not display all the coefficients. They show up overlapped and the user can only see three constants.

**Comment by getwelsim** [comment]
Hello @disla2, thank you for your insightful comment. We can reproduce this issue and will be fixing it.

**Comment by getwelsim** [comment]
Hello @disla2, we have fixed the issue and updated the download. 
You are welcome to use the latest version. Thank you.

![welsim_curvefitter](https://github.com/WelSimLLC/WelSim-Apps/blob/main/galleryCurveFitter/welsim_curvefitter_hyperelastic_polynomial2nd.png?raw=true)

**Comment by disla2** [comment]
Thank you very much

**Comment by getwelsim** [comment]
Thank you. 
I close this issue, if you have any following comments or concerns, feel free to reopen or start a new one.
