### ISSUE TITLE
Enginieering Stress/Strain

### ISSUE THREAD

**Issue by disla2** [WelSimLLC/WelSim-Apps#16]
As it is a common source of errors and doubts between enginieers I would suggest you to add the prefix Enginieering Stress and Enginieering Strain (Biot) as required input data for the Hyperelastic models.

By other hand , which algorithm has Curvefitting2023 implemented,..Levenberg-Marquardt , Nelder_Mead,..?¿?

**Comment by getwelsim** [comment]
@disla2 Thank you for your suggestion. We will add the prefix about that. The curve fitting solver is based on the Levenberg-Marquardt.

**Comment by disla2** [comment]
Thank you very much

**Comment by getwelsim** [comment]
Thank you. 
I close this issue, if you have any following comments or concerns, feel free to reopen or start a new one.
