### ISSUE TITLE
OGDEN N3. Deviatoric Stretches instead of the principal stretches

### ISSUE THREAD

**Issue by disla2** [WelSimLLC/WelSim-Apps#17]
HI,

Nice Software. 
Talking about OGDEN .
I have noticed you are expressing the Strain energy density as a function of the reduced principal stretches- (the deviatoric Stretches instead of the principal stretches)
Is that the Ansys formulation?
Do you have any validation or verification file in which the result compares to Ansys?.
I can’t manage to get good results with this model.

**Comment by getwelsim** [comment]
Hello @disla2, thank you for your comments. We will be investigating this issue. The formulation is Ansys's if I remember correctly. 
It will be very helpful if you can share the test data and the expected parameters with us. The data and parameters can be sent to info@welsim.com.

**Comment by disla2** [comment]
Treloar Standard Test Data as per attached files.
Nominal Stress is expressed in [Kgf/cm2.]
Notice that all txt files generated from CurveFitter shows  **Sub**Independent and **Sub**Dependent. ?¿?
       
[Uniaxial Treloar.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11531614/Uniaxial.Treloar.txt)
[Biaxial Treloar.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11531612/Biaxial.Treloar.txt)
[Pure Shear Planar Treloar.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11531613/Pure.Shear.Planar.Treloar.txt)

See Attached expected result.

![imagen](https://github.com/WelSimLLC/WelSim-Apps/assets/126724892/125c06b2-9a8e-42d9-97b0-01790f050898)

**Comment by getwelsim** [comment]
@disla2 Thank you so much for providing the test data and chart. We will use this data together with others to verify the fitting. Do you mind sharing the expected parameters? 
The strain/stress columns are marked as **sub** because the temperature is the primary variable for the mechanical test data.

**Comment by disla2** [comment]
This could be an excellent reference.

https://www.researchgate.net/publication/301200150_Curve_Fitting_for_Ogden_Yeoh_and_Polynomial_Models
https://fileexchange.scilab.org/toolboxes/350000

**Comment by getwelsim** [comment]
@disla2, thank you for your quick response, and the reference. I will let you know once we have some progress.

**Comment by disla2** [comment]
I could provide the coefficients for the shown graph, but they would relate to the Abaqus formulation.
I also have the Ogden Original paper formulation coefficients but same comment. I don't think it is the same as ANSYS.

**Comment by getwelsim** [comment]
@disla2 Yes, I can understand, thank you for the elaboration. 
To make Curve Fitter better, we may support the Abaqus formulation as well, when the current formulation is resolved.

**Comment by getwelsim** [comment]
Hi @disla2, we improved the CurveFitter a bit for the Ogden models. As shown in the figure below, the parameters and chart look reasonable. We also designed some algorithms to enhance the robustness, and will be implementing them recently.

![welsim_curvefitter_hyperelastic_ogden3](https://github.com/WelSimLLC/WelSim-Apps/assets/30187637/77a7341b-21a8-486d-a839-784b774195b8)

**Comment by disla2** [comment]
Mmmhhh... looks like Shear (green) is fitting the Uniaxial test data Blue. ¿Is that possible?

I have found another reference that fits Treloar with the Ansys formulation. You will need Stress Strain expresed in MPa.
It is from a very known software "polymerfem.com" Published on his post https://polymerfem.com/4-things-you-didnt-know-about-the-ogden-model/

![imagen](https://github.com/WelSimLLC/WelSim-Apps/assets/126724892/1ee1f6e8-73ba-4f46-82a3-14817d65fb1b)
I can see the Ansys coeficients on top. 

[Pure Shear Planar Treloar MPa.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11551635/Pure.Shear.Planar.Treloar.MPa.txt)
[Uniaxial Treloar MPa.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11551636/Uniaxial.Treloar.MPa.txt)
[Biaxial Treloar MPa.txt](https://github.com/WelSimLLC/WelSim-Apps/files/11551637/Biaxial.Treloar.MPa.txt)

**Comment by getwelsim** [comment]
Hi @disla2, thank you for your sharing and comments. We will add some algorithms to make the CurveFitter more robust.

**Comment by lcheng9** [comment]
Hi @disla2, we updated the CurveFitter for better handling the Odgen. If you have any comments or concerns, please let us know. Thank you.

![welsim_curvefitter_hyperelastic_ogden3](https://github.com/WelSimLLC/WelSim-Apps/assets/106984354/e0d93b2b-ad51-4bef-a188-a7d8e9988efb)

**Comment by disla2** [comment]
Wow. Nice and fast fix.
Thank you very much.
 ¿Where could I download the new Curve fitter releases to keep testing.?

**Comment by lcheng9** [comment]
@disla2, Opps, I forgot to post the download link. You are welcome to download the latest version [here](https://github.com/WelSimLLC/WelSim-Apps/releases/download/2.7dev/CurveFitterSetup.exe). This is a quick fix, we are still improving the CurveFitter and the curve fitting module in MatEditor and WelSim. Thank you so much for your insightful comments. I hope CurveFitter can contribute to your projects.

**Comment by lcheng9** [comment]
The issue has been solved, closing now. If you would add comments, please feel free to reopen or start a new post.
