### ISSUE TITLE
Initial temperature does not affect the thermal steady-state analysis

### ISSUE THREAD

**Issue by getwelsim** [WelSimLLC/WelSim-Apps#30]
see the solver issue ticket.
[https://gitlab.com/FrontISTR-Commons/FrontISTR/-/issues/552](https://gitlab.com/FrontISTR-Commons/FrontISTR/-/issues/552)

test case: 073, 072

**Comment by lcheng9** [comment]
As the steady-state analysis, the initial temperature is not supposed to affect the solution.
