### ISSUE TITLE
Missing Tree Items

### ISSUE THREAD

**Issue by TimHoehn48** [WelSimLLC/WelSim-Apps#44]
Brand new user and working on my first project. My tree display is missing anything choices under the "Answers" Object. I have no way to choose which solver to use. Any idea what's going on and how to fix it?

UPDATE - Apparently I have a newer version of the software and things are located in different area. I eventually found what I needed.

![Welsim Problem](https://github.com/WelSimLLC/WelSim-Apps/assets/145040842/3f36f734-96fa-44ca-b582-a339b60ddab4)

**Comment by getwelsim** [comment]
Hi @TimHoehn48 , Thank you for using WelSim and bringing up your concerns. Yes, the Solver property has been adjusted to the Study Setting object. We will update the tutorial/documentation according. Please feel free to start a new issue or reopen this one if you have any comments.
