### ISSUE TITLE
 curvefitter

### ISSUE THREAD

**Issue by j-sen123** [WelSimLLC/WelSim-Apps#50]
The curvefitter software only has built-in formula equations. Can you add a custom function equation function? Thank you!

**Comment by lcheng9** [comment]
Thank you for your comments. 

It is difficult to support customized functions because each type of function may use different solving schemes. If you need specific functions, please let us know we always try to deliver the new equations as soon as possible.

**Comment by j-sen123** [comment]
I want to fit a hyperelastic stress-strain curve at different strain rates. Add strain rate related terms (exponential, logarithmic or polynomial) to the original hyperelastic stress-strain relationship.
![image](https://github.com/WelSimLLC/WelSim-Apps/assets/126223362/b7936b19-2aea-4ca5-8b56-c73520dec256)

**Comment by j-sen123** [comment]
![image](https://github.com/WelSimLLC/WelSim-Apps/assets/126223362/a0d61ff0-3cd9-4e2d-ab9c-5cf8d814ccd7)

**Comment by lcheng9** [comment]
Thank you for providing the details. 
This equation is the uniaxial tension with an added strain rate term. The exact term still depends on the energy functional. Do you have a preferred hyperelastic model? such as Polynomial, Neo-Hookean, etc. If I am understanding correctly, the parameter \mu is the fitting coefficient, and the \epsilon^{star} is given for a set of strain-stress?

**Comment by j-sen123** [comment]
My current preferred hyperelastic model is Mooney-Rivlin 5 parameters.
![image](https://github.com/WelSimLLC/WelSim-Apps/assets/126223362/bd1c53d7-3a2a-4874-a8a2-564fd7c1d868)
Yes, the parameter \mu is the fitting coefficient, e_ is the strain rate and e_ 0 is the reference strain rate.

**Comment by j-sen123** [comment]
I hope that the strain rate related term can be set in a form by myself, because I want to find the most appropriate form to fit the curve. If that's not possible, I currently use the strain rate term as shown.
![image](https://github.com/WelSimLLC/WelSim-Apps/assets/126223362/60213d73-c45b-4dc9-b046-b4744ff1c987)
A,B,C,D are parameters.Thanks for your help.

**Comment by lcheng9** [comment]
Thank you for letting me know your preference. 
We will try to fit this function. Since there are nine parameters in total, the convergence is not guaranteed. I will keep you posted here once the feature becomes available.

**Comment by j-sen123** [comment]
Thank you very much, looking forward to your good news

**Comment by getwelsim** [comment]
@j-sen123 We tried to fit this function without success, the solve cannot converge. This function may not be shipped before we figure out a better solving scheme, I am sorry for the unavailability at this moment, if you have any comments or other curves to fit, please feel free to let us know. Thank you.
