### ISSUE TITLE
MatEditor Tabular Data

### ISSUE THREAD

**Issue by myareny** [WelSimLLC/WelSim-Apps#73]
I need to make curve fitting for the material. I accidentally closed the tab where the test data will be entered and I cannot open it again. I couldn't find any information about this on the internet. I deleted the program and reinstalled it. The window where I can enter the test data still does not open. How can I solve this in the application?

**Comment by lcheng9** [comment]
Hi @myareny, you can right mouse button click on the toolbar space, and toggle on the Tabular Data Window.
